// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Config struct {
	ServerID  string
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Server struct {
	ID        string
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
